### ISSUE TITLE
Instructions for building the driver on OpenWrt

### ISSUE THREAD

**Issue by LuisMitaHL** [henkv1/rtw88-usb-openwrt#1]
Hi,
I tried cloning the repo on package/kernel/rtw88 but I have this error
```
  CC [M]  /media/Standard/LooperWrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/rtw88-usb-0~HEAD/main.o
In file included from /media/Standard/LooperWrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/rtw88-usb-0~HEAD/main.c:7:
/media/Standard/LooperWrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/rtw88-usb-0~HEAD/main.h:47:1: error: redefinition of 'cfg80211_ssid_eq'
   47 | cfg80211_ssid_eq(struct cfg80211_ssid *a, struct cfg80211_ssid *b)
      | ^~~~~~~~~~~~~~~~
In file included from /media/Standard/LooperWrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211/net/mac80211.h:22,
                 from /media/Standard/LooperWrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/rtw88-usb-0~HEAD/main.h:12:
/media/Standard/LooperWrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/mac80211/net/cfg80211.h:7303:1: note: previous definition of 'cfg80211_ssid_eq' with type 'bool(struct cfg80211_ssid *, struct cfg80211_ssid *)' {aka '_Bool(struct cfg80211_ssid *, struct cfg80211_ssid *)'}
 7303 | cfg80211_ssid_eq(struct cfg80211_ssid *a, struct cfg80211_ssid *b)
      | ^~~~~~~~~~~~~~~~
make[5]: *** [scripts/Makefile.build:243: /media/Standard/LooperWrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/rtw88-usb-0~HEAD/main.o] Error 1
make[4]: *** [/media/Standard/LooperWrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.6.45/Makefile:1921: /media/Standard/LooperWrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/rtw88-usb-0~HEAD] Error 2

```

Do you have instructions for building the modules?

**Comment by henkv1** [comment]
I added some installation instructions. But it was only tested with the 23.05.4 SDK. What version are you using?

**Comment by castillofrancodamian** [comment]
@henkv1 And how do I include it in an OpenWrt image?

**Comment by henkv1** [comment]
The compiled package is named kmod-rtw88-usb_* and you can find it in the bin/target/<architecture>/<model>/packages/ directory. You can copy it to your device and install it using opkg install <package>. Please note that you also need to install the firmware packages for your device to make the module work.

**Comment by henkv1** [comment]
@LuisMitaHL I fixed the compilation for the current snapshot releases. I think this will fix your compilation issues as well.

**Comment by castillofrancodamian** [comment]
> The compiled package is named kmod-rtw88-usb_* and you can find it in the bin/target/_architecture_/_model_/packages/ directory. You can copy it to your device and install it using opkg install _package_. Please note that you also need to install the firmware packages for your device to make the module work.

The only rtw88 like files I found are `kmod-rtw88` and `kmod-rtw88-usb`. My Wi-Fi adapter has a RTW8812AU chipset. What would be the correct firmware? Also, when trying to install those files in OpenWrt, I get an error:

![Captura de pantalla_20240828_171919](https://github.com/user-attachments/assets/587c4a8c-3466-42a5-bb6b-d74a1955518d)

**Comment by henkv1** [comment]
I don't think there is a firmware package for rtl8812au. You can download it manually from https://github.com/lwfinger/rtw88/tree/master/firmware and copy it to /lib/firmware/rtw88/. I will see if I can include the firmware in the package.

**Comment by castillofrancodamian** [comment]
Is it possible to compile this package only and not compile the other packages as well?

**Comment by castillofrancodamian** [comment]
Could you please update the patches to be compatible with new versions of OpenWrt core packages?
